version: '3.4'
services:
  api:
    platform: linux/amd64
    build: backend/movies/
    ports:
      - ${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}
    environment:
      spring.datasource.url: jdbc:mysql://database:${MYSQLDB_DOCKER_PORT}/${MYSQLDB_DATABASE}?createDatabaseIfNotExist=true
      spring.datasource.driverClassName: com.mysql.cj.jdbc.Driver
      spring.datasource.username: ${MYSQLDB_USER}
      spring.datasource.password: ${MYSQLDB_PASSWORD}
      spring.flyway.validateOnMigrate: false
      spring.flyway.cleanDisabled: false
      spring.flyway.locations: classpath:db/migration/mysql

    depends_on:
      - database

  web:
    platform: linux/amd64
    build: frontend/
    ports:
      - ${WEB_LOCAL_PORT}:${WEB_DOCKER_PORT}
    environment:
      API_URL: http://api:${SPRING_DOCKER_PORT}
    depends_on:
      - api

  database:
    platform: linux/amd64
    image: mysql:8.0-oracle
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: superprice
      MYSQL_ROOT_PASSWORD: ${MYSQLDB_PASSWORD}
    ports:
      - ${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}
    volumes:
      - db:/var/lib/mysql

  adminer:
    platform: linux/amd64
    image: adminer
    restart: always
    ports:
      - ${ADMINER_LOCAL_PORT}:${ADMINER_DOCKER_PORT}

volumes:
  db: