CREATE TEMPORARY TABLE tmp_supermarket_product (
    price decimal(8,2),
    supermarket_name varchar(255),
    product_name varchar(255)
);

INSERT INTO tmp_supermarket_product(price, supermarket_name, product_name) VALUES
(3.40,'Coles','Coca - Cola Classic Soft Drink 1.25L'),
(3.55,'Woolworths','Coca - Cola Classic Soft Drink 1.25L'),
(3.55,'IGA','Coca - Cola Classic Soft Drink 1.25L'),
(3.40,'Coles','Coca - Cola Zero Sugar Soft Drink Bottle 1.25l'),
(3.55,'Woolworths','Coca - Cola Zero Sugar Soft Drink Bottle 1.25l'),
(3.55,'IGA','Coca - Cola Zero Sugar Soft Drink Bottle 1.25l'),
(3.40,'Coles','Coca - Cola Vanilla Soft Drink Bottle 1.25l'),
(3.55,'Woolworths','Coca - Cola Vanilla Soft Drink Bottle 1.25l'),
(3.55,'IGA','Coca - Cola Vanilla Soft Drink Bottle 1.25l'),
(3.40,'Coles','Sprite Lemonade Soft Drink 1.25L'),
(3.55,'Woolworths','Sprite Lemonade Soft Drink 1.25L'),
(3.55,'IGA','Sprite Lemonade Soft Drink 1.25L'),
(3.40,'Coles','Sprite Zero Sugar Lemonade Soft Drink Bottle 1.25l'),
(3.55,'Woolworths','Sprite Zero Sugar Lemonade Soft Drink Bottle 1.25l'),
(3.55,'IGA','Sprite Zero Sugar Lemonade Soft Drink Bottle 1.25l'),
(3.40,'Coles','Sprite Lemon+ Soft Drink 1.25l'),
(3.55,'Woolworths','Sprite Lemon+ Soft Drink 1.25l'),
(3.55,'IGA','Sprite Lemon+ Soft Drink 1.25l'),
(2.85,'Coles','Mountain Dew Soft Drink Energised Bottle 1.25l'),
(3.00,'Woolworths','Mountain Dew Soft Drink Energised Bottle 1.25l'),
(3.00,'IGA','Mountain Dew Soft Drink Energised Bottle 1.25l'),
(15.00,'Coles','Mountain Dew Soft Drink Cans 375ml X10 Pack'),
(16.50,'Woolworths','Mountain Dew Soft Drink Cans 375ml X10 Pack'),
(16.50,'IGA','Mountain Dew Soft Drink Cans 375ml X10 Pack'),
(3.95,'Woolworths','Mountain Dew Major Melon Soft Drink Bottle 600ml'),
(3.00,'Coles','Driscoll''s Fresh Blueberries Punnet 170g'),
(2.80,'Woolworths','Driscoll''s Fresh Blueberries Punnet 170g'),
(4.50,'Coles','Fresh Raspberry 125g'),
(5.50,'Woolworths','Fresh Raspberry 125g'),
(6.00,'Coles','Blackberry Fresh 125g'),
(6.50,'Woolworths','Blackberry Fresh 125g'),
(7.00,'Coles','Arnott''s Cream Favourites Assorted Biscuits 500g'),
(7.00,'Woolworths','Arnott''s Cream Favourites Assorted Biscuits 500g'),
(7.00,'IGA','Arnott''s Cream Favourites Assorted Biscuits 500g'),
(3.30,'Coles','Arnott''s Scotch Finger Plain Biscuits 250g'),
(3.30,'Woolworths','Arnott''s Scotch Finger Plain Biscuits 250g'),
(3.30,'IGA','Arnott''s Scotch Finger Plain Biscuits 250g'),
(5.00,'Coles','Arnott''s Family Favourites Assorted Biscuits 500g'),
(5.00,'Woolworths','Arnott''s Family Favourites Assorted Biscuits 500g'),
(5.00,'IGA','Arnott''s Family Favourites Assorted Biscuits 500g'),
(2.20,'Coles','Kitkat 4 Finger Milk Chocolate Bar 45g'),
(2.20,'Woolworths','Kitkat 4 Finger Milk Chocolate Bar 45g'),
(2.20,'IGA','Kitkat 4 Finger Milk Chocolate Bar 45g'),
(2.20,'Coles','Nestle Aero Peppermint 40g Bar'),
(2.20,'Woolworths','Nestle Aero Peppermint 40g Bar'),
(2.20,'IGA','Nestle Aero Peppermint 40g Bar'),
(5.50,'Coles','Nestle Smarties Chocolate Block 180g'),
(5.50,'Woolworths','Nestle Smarties Chocolate Block 180g'),
(5.50,'IGA','Nestle Smarties Chocolate Block 180g'),
(4.90,'Coles','Helga''s Bread Traditional Wholemeal 750g'),
(4.90,'Woolworths','Helga''s Bread Traditional Wholemeal 750g'),
(6.45,'IGA','Helga''s Bread Traditional Wholemeal 750g'),
(4.90,'Coles','Helga''s Grain Bread Mixed Grain 850g'),
(4.90,'Woolworths','Helga''s Grain Bread Mixed Grain 850g'),
(6.45,'IGA','Helga''s Grain Bread Mixed Grain 850g'),
(4.90,'Coles','Helga''s Pumpkin Seed & Grain 720g'),
(4.90,'Woolworths','Helga''s Pumpkin Seed & Grain 720g'),
(6.45,'IGA','Helga''s Pumpkin Seed & Grain 720g'),
(3.70,'Coles','Primo Turkey Breast 80g'),
(3.70,'Woolworths','Primo Turkey Breast 80g'),
(3.70,'IGA','Primo Turkey Breast 80g'),
(3.70,'Coles','Primo Pastrami 80g'),
(3.70,'Woolworths','Primo Pastrami 80g'),
(3.70,'IGA','Primo Pastrami 80g'),
(3.70,'Coles','Primo Champagne Ham Thinly Sliced 100g'),
(3.70,'Woolworths','Primo Champagne Ham Thinly Sliced 100g'),
(3.70,'IGA','Primo Champagne Ham Thinly Sliced 100g'),
(13.60,'Woolworths','Quilton Toilet Tissue 3 Ply White 180 Sheets 24 Pack'),
(12.00,'Woolworths','Quilton Double Length Toilet Tissue 3ply White 360 Sheets 8 Pack'),
(8.60,'Woolworths','Quilton Classic Toilet Tissue 3 Ply 8 Pack'),
(54.00,'Coles','Finish Ultimate Pro Dishwasher Tablets Lemon 46 Pack'),
(54.00,'Woolworths','Finish Ultimate Pro Dishwasher Tablets Lemon 46 Pack'),
(11.50,'Coles','Finish Rinse & Shine Aid Liquid Regular 500ml'),
(11.50,'Woolworths','Finish Rinse & Shine Aid Liquid Regular 500ml'),
(24.00,'Coles','Finish Concentrated Dishwasher Powder Classic Lemon Sparkle 2kg'),
(24.00,'Woolworths','Finish Concentrated Dishwasher Powder Classic Lemon Sparkle 2kg'),
(3.00,'Coles','Kleenex Aloe Vera & Vitamin E 3 Ply Facial Tissues 95 Pack'),
(3.00,'Woolworths','Kleenex Aloe Vera & Vitamin E 3 Ply Facial Tissues 95 Pack'),
(2.60,'IGA','Kleenex Aloe Vera & Vitamin E 3 Ply Facial Tissues 95 Pack'),
(3.00,'Coles','Kleenex Everyday 2 Ply Facial Tissues 200 Pack'),
(3.00,'Woolworths','Kleenex Everyday 2 Ply Facial Tissues 200 Pack'),
(3.00,'IGA','Kleenex Everyday 2 Ply Facial Tissues 200 Pack'),
(3.50,'Coles','Kleenex Large & Thick 3 Ply Facial Tissues 95 Pack'),
(3.50,'Woolworths','Kleenex Large & Thick 3 Ply Facial Tissues 95 Pack'),
(3.15,'IGA','Kleenex Large & Thick 3 Ply Facial Tissues 95 Pack'),
(5.00,'Coles','Huggies Thick Baby Wipes Fragrance Free 80 Pack'),
(5.00,'Woolworths','Huggies Thick Baby Wipes Fragrance Free 80 Pack'),
(5.00,'IGA','Huggies Thick Baby Wipes Fragrance Free 80 Pack'),
(5.00,'Coles','Huggies Thick Baby Wipes Coconut Oil 80 Pack'),
(5.00,'Woolworths','Huggies Thick Baby Wipes Coconut Oil 80 Pack'),
(5.00,'IGA','Huggies Thick Baby Wipes Coconut Oil 80 Pack'),
(5.00,'Woolworths','Huggies Thick Baby Wipes Cucumber & Aloe 80 Pack'),
(5.00,'Coles','Huggies Thick Baby Wipes Cucumber & Aloe 80 Pack'),
(6.90,'Coles','A2 Full Cream Milk 2l'),
(6.90,'Woolworths','A2 Full Cream Milk 2l'),
(6.90,'IGA','A2 Full Cream Milk 2l'),
(6.90,'Coles','A2 Light Milk 2l'),
(6.90,'Woolworths','A2 Light Milk 2l'),
(6.90,'IGA','A2 Light Milk 2l'),
(7.30,'Coles','A2 Milk Lactose Free Light Milk 2l'),
(7.20,'Woolworths','A2 Milk Lactose Free Light Milk 2l'),
(6.00,'Coles','Vip Chunkers With Beef, Peas & Carrot 1kg'),
(6.00,'Woolworths','Vip Chunkers With Beef, Peas & Carrot 1kg'),
(7.00,'Woolworths','Vip Paws Adult Chilled Fresh Dog & Cat Food Mince 1kg'),
(7.00,'IGA','Vip Paws Adult Chilled Fresh Dog & Cat Food Mince 1kg'),
(7.00,'Woolworths','Vip Paws Adult Chilled Fresh Dog & Cat Food Chicken Mince 1kg'),
(55.00,'Coles','Asahi Super Dry Lager Bottles 330ml X24 Case'),
(61.00,'Woolworths','Asahi Super Dry Lager Bottles 330ml X24 Case'),
(13.00,'Coles','Asahi Super Dry 0% Bottles 330ml X 6 Pack'),
(14.50,'Woolworths','Asahi Super Dry 0% Bottles 330ml X 6 Pack'),
(25.00,'Woolworths','Asahi Super Dry Lager Bottles 330ml X 6 Pack'),
(52.00,'Coles','Bundaberg Underproof Rum 700ml'),
(53.00,'Woolworths','Bundaberg Underproof Rum 700ml'),
(6.45,'Coles','Bundaberg Sparkling Passionfruit Drink 375ml X4 Pack'),
(7.00,'Woolworths','Bundaberg Sparkling Passionfruit Drink 375ml X4 Pack'),
(7.00,'IGA','Bundaberg Sparkling Passionfruit Drink 375ml X4 Pack'),
(7.00,'Woolworths','Bundaberg Sparkling Guava Sparkling Drink 375ml X4 Pack'),
(7.00,'IGA','Bundaberg Sparkling Guava Sparkling Drink 375ml X4 Pack'),
(14.50,'Coles','Ben & Jerry’s Ice Cream Tub Chocolate Chip Cookie Dough 458 Ml'),
(14.50,'Woolworths','Ben & Jerry’s Ice Cream Tub Chocolate Chip Cookie Dough 458 Ml'),
(14.50,'IGA','Ben & Jerry’s Ice Cream Tub Chocolate Chip Cookie Dough 458 Ml'),
(14.50,'Coles','Ben & Jerry''s Topped Tirumisu Ice Cream Tub 436ml'),
(14.50,'Woolworths','Ben & Jerry''s Topped Tirumisu Ice Cream Tub 436ml'),
(14.50,'Coles','Ben & Jerry’s Ice Cream Tub Chocolate Fudge Brownie 458 Ml'),
(14.50,'Woolworths','Ben & Jerry’s Ice Cream Tub Chocolate Fudge Brownie 458 Ml');

INSERT INTO supermarket_product(price, supermarket_id, product_id)
SELECT price,
(SELECT MAX(id) FROM supermarket WHERE name = supermarket_name),
(SELECT MAX(id) FROM product WHERE name = product_name)
FROM tmp_supermarket_product;

DROP TABLE tmp_supermarket_product;








